title: Open Definition
markdown: kramdown
googleanalytics: UA-8271754-4
github: http://github.com/okfn/opendefinition
url: http://opendefinition.org
permalink: /:year/:month/:day/:title/
od_current_version: 2.1

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
