title: Open Definition
markdown: kramdown
googleanalytics: UA-8271754-4
repository: okfn/opendefinition
url: https://opendefinition.org
permalink: /:year/:month/:day/:title/
od_current_version: '2.1'
sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-github-metadata

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - script
  - vendor
